[package]
name = "alpymistctl"
description = "Alpymist system control CLI."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
alpymist-core = { workspace = true }
alpymist-hwprobe = { workspace = true }
clap = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true
