[package]
name = "alpymist-glesprobe"
description = "Queries OpenGL ES capability via EGL. One of the two crates in Alpymist permitted to use unsafe."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
alpymist-core = { workspace = true }
khronos-egl = { workspace = true }
libloading = { workspace = true }

[lints]
workspace = true
