//! Generating the installer's keyboard layout and time zone lists.
//!
//! Read from the packages Alpine's own `setup-keymap` and `setup-timezone` read,
//! so every entry the installer offers is one those tools accept. Run inside the
//! Alpine builder, where `kbd-bkeymaps` and `tzdata` can be installed; the output
//! is committed, so building the installer never needs either package.

use anyhow::{Context, Result};
use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::Path;

/// Layout directories that are not named for a country.
const NOT_COUNTRIES: [(&str, &str); 5] = [
    ("ara", "Arabic"),
    ("brai", "Braille"),
    ("epo", "Esperanto"),
    ("latam", "Latin America"),
    ("gb", "United Kingdom"),
];

/// Write `keymaps.tsv` and `timezones.tsv` into `out`.
pub fn generate(bkeymaps: &Path, zoneinfo: &Path, out: &Path) -> Result<()> {
    let countries = countries(&zoneinfo.join("iso3166.tab"))?;
    std::fs::create_dir_all(out)?;

    let keymaps = keymaps(bkeymaps, &countries)?;
    std::fs::write(out.join("keymaps.tsv"), &keymaps)?;

    let zones = zones(&zoneinfo.join("zone.tab"), &countries)?;
    std::fs::write(out.join("timezones.tsv"), &zones)?;

    println!(
        "wrote {} keymaps and {} time zones to {}",
        keymaps.lines().filter(|l| !l.starts_with('#')).count(),
        zones.lines().filter(|l| !l.starts_with('#')).count(),
        out.display()
    );
    Ok(())
}

/// Two-letter code, lower case, to country name.
fn countries(iso3166: &Path) -> Result<BTreeMap<String, String>> {
    let text = std::fs::read_to_string(iso3166)
        .with_context(|| format!("reading {}", iso3166.display()))?;
    Ok(text
        .lines()
        .filter(|l| !l.starts_with('#'))
        .filter_map(|l| l.split_once('\t'))
        .map(|(code, name)| (code.to_ascii_lowercase(), name.trim().to_string()))
        .collect())
}

/// `layout<TAB>variant<TAB>name`, one per keymap file, sorted.
fn keymaps(root: &Path, countries: &BTreeMap<String, String>) -> Result<String> {
    let mut rows = Vec::new();
    for layout in std::fs::read_dir(root).with_context(|| format!("reading {}", root.display()))? {
        let layout = layout?;
        if !layout.file_type()?.is_dir() {
            continue;
        }
        let code = layout.file_name().to_string_lossy().into_owned();
        let name = NOT_COUNTRIES
            .iter()
            .find(|(c, _)| *c == code)
            .map(|(_, n)| (*n).to_string())
            .or_else(|| countries.get(&code).cloned())
            .unwrap_or_else(|| code.clone());
        for file in std::fs::read_dir(layout.path())? {
            let file = file?.file_name().to_string_lossy().into_owned();
            if let Some(variant) = file.strip_suffix(".bmap.gz") {
                rows.push(format!("{code}\t{variant}\t{name}"));
            }
        }
    }
    rows.sort();
    Ok(with_header(
        "layout\tvariant\tname — generated by `cargo xtask installer-data` from kbd-bkeymaps",
        &rows,
    ))
}

/// `zone<TAB>country code<TAB>country name`, sorted by zone, plus UTC.
fn zones(zone_tab: &Path, countries: &BTreeMap<String, String>) -> Result<String> {
    let text = std::fs::read_to_string(zone_tab)
        .with_context(|| format!("reading {}", zone_tab.display()))?;
    let mut rows: Vec<String> = text
        .lines()
        .filter(|l| !l.starts_with('#'))
        .filter_map(|l| {
            let mut fields = l.split('\t');
            let code = fields.next()?.to_ascii_lowercase();
            let zone = fields.nth(1)?;
            let name = countries.get(&code).cloned().unwrap_or_default();
            Some(format!("{zone}\t{code}\t{name}"))
        })
        .collect();
    // Not a country's zone, so zone.tab leaves it out; it is also the default.
    rows.push("UTC\t\tCoordinated Universal Time".into());
    rows.sort();
    Ok(with_header(
        "zone\tcountry\tname — generated by `cargo xtask installer-data` from tzdata",
        &rows,
    ))
}

fn with_header(header: &str, rows: &[String]) -> String {
    let mut out = format!("# {header}\n");
    for row in rows {
        let _ = writeln!(out, "{row}");
    }
    out
}
